# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('MENTOR', 'Mentor'), ('MENTEE', 'Mentee'), ('ORGANIZATION', 'Organization')], max_length=1)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Profile')),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Profile')),
                ('specialty', models.CharField(choices=[('SPIRITUAL', 'Spiritual'), ('PEER', 'Peer'), ('COMMUNICATION', 'Communication'), ('EDUCATION', 'Education'), ('PROFESSIONAL', 'Professional')], max_length=1)),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Profile')),
            ],
            bases=('profiles.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
