# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='specialty',
            field=models.CharField(choices=[('SPIRITUAL', 'Spiritual'), ('PEER', 'Peer'), ('COMMUNICATION', 'Communication'), ('EDUCATION', 'Education'), ('PROFESSIONAL', 'Professional')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('MENTOR', 'Mentor'), ('MENTEE', 'Mentee'), ('ORGANIZATION', 'Organization')], max_length=64),
        ),
    ]
