# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171112_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
