# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 02:55
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=stdimage.models.StdImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
